server:
  port: 9090
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://tyb:tyb1222@eureka1:7001/eureka,http://tyb:tyb1222@eureka2:7002/eureka
feign:
  hystrix:
    enabled: true

